### PR TITLE
Provide installation guidance

### PR DESCRIPTION
**Pull request by tomkerkhove**
Provide installation guidance and link to NuGet package.

Closes https://github.com/cloudevents/sdk-csharp/issues/15

### CODE REVIEW

**Comment by jskeet** [comment]
@tomkerkhove: I don't know whether the DCO checker was added after you'd raised this PR, but could you amend your commit message to include a sign-off ([example](https://github.com/cloudevents/sdk-csharp/commit/0acb17529a419dcda5d72cfe5724b26423aa2e48))?

**Comment by tomkerkhove** [comment]
Happy to change to dotnet approach if you prefer @jskeet?

It was not there yet I think but happy to change, but will wait for your feedback on the above

**Comment by jskeet** [comment]
> Happy to change to dotnet approach if you prefer @jskeet?

I'd actually suggest not including any installation instructions - but possibly include the NuGet package name in the text so it's easy to copy/paste. So something like:

> The SDK is available via the [CloudNative.CloudEvents NuGet package](https://www.nuget.org/packages/CloudNative.CloudEvents/)

I'd hope that anyone wanting to use the SDK can either follow the instructions on the NuGet package page, or will already know how to install a NuGet package anyway.

(It's slightly annoying that it's natural to put the package name in the link text but that makes it slightly harder to copy/paste if you don't want to follow the link.)

I don't know whether the other packages (e.g. CloudNative.CloudEvents.AspNetCore) should also be listed - what do you think?

**Comment by jskeet** [comment]
We've now included the package names in the [user guide](https://github.com/cloudevents/sdk-csharp/blob/master/docs/guide.md) which is linked from the top-level README. I'll close this PR as I don't think it's needed any more (and would certainly need rebasing) - but please don't let that deter you from further docs improvements :)

**Pull request closed without merging**
