### PR TITLE
Change `Uri` reference to use the `UriKind` overload in the User Guide

### PR DESCRIPTION
**Pull request by VisualBean**

### CODE REVIEW

**Review by jskeet — APPROVED** [review]
Fine with this as it is - I wonder whether it *might* be worth leaving one as absolute, just to make it clearer that both are okay? (The examples in https://github.com/cloudevents/spec/blob/master/spec.md#source-1 include absolute ones as well.)

**Comment by VisualBean** [comment]
> https://github.com/cloudevents/spec/blob/master/spec.md#source-1

Good point. Should we leave line 237 as it was originally?

**Comment by VisualBean** [comment]
> Fine with this as it is - I wonder whether it _might_ be worth leaving one as absolute, just to make it clearer that both are okay? (The examples in https://github.com/cloudevents/spec/blob/master/spec.md#source-1 include absolute ones as well.)

Good point. Should we leave line 237 as it was originally?

**Comment by jskeet** [comment]
> Good point. Should we leave line 237 as it was originally?

Either that or 324 - I don't mind which.

Could you rebase your PR against the current HEAD, btw? It's possible that GitHub would just do the right thing, but I'll be more confident if the PR only has a single commit :)

**Comment by VisualBean** [comment]
> > Good point. Should we leave line 237 as it was originally?
> 
> Either that or 324 - I don't mind which.
> 
> Could you rebase your PR against the current HEAD, btw? It's possible that GitHub would just do the right thing, but I'll be more confident if the PR only has a single commit :)

Yeah I noticed the weirdness and rebased.

**Comment by jskeet** [comment]
Hmm... I'm still seeing 5 commits at the moment. Might it be easiest at this stage if I just create a new PR myself and merge it in?

**Comment by VisualBean** [comment]
> Hmm... I'm still seeing 5 commits at the moment. Might it be easiest at this stage if I just create a new PR myself and merge it in?

Oh for crying out loud. 
Yeah maybe that will be better 😂

**Comment by jskeet** [comment]
As it happens, I'd forgotten that I'm keeping the docs samples as actual source too, so the new PR will be slightly cleaner :)

**Pull request closed without merging**
