### PR TITLE
Adds RabbitMQ bindings

### PR DESCRIPTION
**Pull request by antiblue**
PR for #310 
Adds AMQP 0.9.1 protocol binding using the [RabbitMq.Client](https://www.rabbitmq.com/client-libraries/dotnet-api-guide#overview).

It follows the ["RabbitMQ Protocol Binding for CloudEvents" specification](https://github.com/knative-extensions/eventing-rabbitmq/blob/main/cloudevents-protocol-spec/spec.md).

### CODE REVIEW

**Comment by jskeet** [comment]
Will try to review this next week.

**Comment by clemensv** [comment]
There is no spec'd protocol binding for AMQP 0.9.1. AMQP 0.9.1 is an expired draft of the AMQP protocol and never made it to standardization. That excludes AMQP 0.9.1 per https://github.com/cloudevents/spec/blob/main/cloudevents/primer.md#qualifying-protocols-and-encodings 

What can be done is to submit a binding spec into the "proprietary specs" section for RabbitMQ analog to RocketMQ. 
https://github.com/cloudevents/spec/blob/main/cloudevents/proprietary-specs.md

That can then be composed with, but arguably not embedded into the official SDK.

**Comment by antiblue** [comment]
> Edit: I only just see that the RMQ binding exists but isn't registered in our proprietary spec list. That should be added. Still skeptical whether a proprietary client should be in the offical SDK.

That is a valid point.

**Comment by antiblue** [comment]
IMHO Clemens arguments are a reason to close this pull request.

**Comment by jskeet** [comment]
Thanks, doing so now.

**Pull request closed without merging**
