### PR TITLE
Fixed link to JsonEventFormatter

### PR DESCRIPTION
**Pull request by abatishchev**

### CODE REVIEW

**Comment by jskeet** [comment]
Thanks for the fix - please could you amend your commit to have a "Signed-off by" line? (See other commits for what this looks like.)

**Comment by abatishchev** [comment]
@jskeet sure, done! I saw the check pending a sign off but though it would be a reviewer, not the author.

**Comment by jskeet** [comment]
Hmm... I have no idea why the DCO is still failing. I'll see if I can resolve it manually.

**Comment by abatishchev** [comment]
Could it be due to the dual nature of my account? I'm a Microsoft employee and `git commit -s` adds my microsoft.com email but this contribution is in personal capacity, hence I used my personal email.

**Comment by jskeet** [comment]
Ah - I've found the problem - you've signed it off with your gmail account, but the commit uses the Microsoft account.
(Crossing comments...)
If you can amend the author of the commit to be your gmail account, I'd expect that to fix it.

**Comment by abatishchev** [comment]
Yeah, it says:

> Commit sha: [1f6a316](https://github.com/cloudevents/sdk-csharp/pull/212/commits/1f6a3163c09730153e72e104013c7659141d6f90), Author: Alex Batishchev, Committer: Alex Batishchev; Expected "Alex Batishchev [alexbat@microsoft.com](mailto:alexbat@microsoft.com)", but got "Alex Batishchev [abatishchev@gmail.com](mailto:abatishchev@gmail.com)".

The problem is that I don't have another account, it's both my work and personal. But has GitHub Enterprise MFA enabled.

**Comment by abatishchev** [comment]
> (Apologies for the bureaucracy here...)

np! totally get it. the same reason I don't want to use my work email, if it's ok with you.

**Comment by abatishchev** [comment]
Let me try to edit local repo settings.

**Comment by jskeet** [comment]
Right, it's a single GitHub account... I suspect if you pull it locally, you could amend it that way.

Alternatively, I could just make the same change myself, if you're not bothered about not being in the commit history ;)

**Comment by abatishchev** [comment]
Yay, worked!

```
[user]
	name = Alexander Batishchev
	email = abatishchev@gmail.com
```

Here's what was needed in `.git\config`.

**Comment by jskeet** [comment]
Bingo - thanks!

**Comment by abatishchev** [comment]
Thanks! Learned something new along the way :)

**Pull request merged**
