### PR TITLE
fix: adding missing mandatory Id attribute

### PR DESCRIPTION
**Pull request by shef**
without Id attribute in cloudEvent the program doesn't work and return an error:
`Unhandled exception. System.ArgumentException: CloudEvent is missing required attributes: id (Parameter 'cloudEvent')`

### CODE REVIEW

**Comment by jskeet** [comment]
Thanks for this. Please could you amend your commit to include a "Signed-off-by" line? If that's fiddly with the GitHub UI, I'm happy to create an equivalent PR myself.

**Comment by shef** [comment]
> 

please go ahead! i got commit message with my email privacy feature on hence signoff will not match the emails :D

**Comment by jskeet** [comment]
Great - will do that on Monday, thanks :)

**Comment by jskeet** [comment]
Closing in favor of #215.

**Pull request closed without merging**
